const types = {
    GET_LEADS: 'GET_LEADS',
    DELETE_LEAD: 'DELETE_LEAD',
    ADD_LEAD: 'ADD_LEAD',
    GET_ERRORS: 'GET_ERRORS',
    GET_MESSAGES: 'GET_MESSAGES',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    USER_LOADING: 'USER_LOADING',
    USER_LOADED: 'USER_LOADED',
    AUTH_ERROR: 'AUTH_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL'

}
export default types;
